package negocio;
import java.util.List;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Servicio.java
//  @ Date : 06/04/2015
//  @ Author : 
//
//




public class Servicio
{
	private String tipoServicio;
	private String denominacion;
	private List<Costo> costos;
	public Float calcularCostoServicio()
	{
		return null;
	
	}
}
