package bean;
import java.util.List;

import org.hibernate.annotations.Entity;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project , Untitled
//  @ File Name , AdministradorVarios.java
//  @ Date , 06/04/2015
//  @ Author , 
//
//



@Entity
public class AdministradorVariosBean
{
	
	private List<ClienteBean> clientes;
	private List<SucursalBean> sucursales; 
	private List<EmpleadoBean> empleados;
	private List<VehiculoBean> vehiculos;
	private List<ProveedorBean> proveedores; 
	
	
	
}
