package bean;
import java.util.List;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project , Untitled
//  @ File Name , AdministradorViaje.java
//  @ Date , 06/04/2015
//  @ Author , 
//
//




public class AdministradorViajeBean
{
	private List<ViajeBean> viajes;
	private List<ProveedorBean> proveedores;
	private List<SucursalBean> sucursales;
	private List<ViajeBean> listarSolicitudesDeViajePorSucursal(SucursalBean suc)
	{
		return viajes;
	
	}
	
	public void generarViaje()
	{
	
	}
	
	private void VerificarDisponibilidadVehiculo()
	{
	
	}
	
	public void asignarVehiculo(ViajeBean vh, VehiculoBean vi)
	{
	
	}
	
	private void buscarProveedor()
	{
	
	}
	
	public void asignarProveedor(ViajeBean pr, ProveedorBean vi)
	{
	
	}
	
	public List solicitarCotizacion(ServicioBean serv)
	{
		return proveedores;
	
	}
	
	private List<ServicioBean> consultarServiciosAdicionales(String tipoServ)
	{
		return null;
	
	}
	
	public void contratarServicioAdicional(ServicioBean vi, ViajeBean serv)
	{
	
	}
}
