package bean;
import java.util.Date;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Costo.java
//  @ Date : 06/04/2015
//  @ Author : 
//
//




public class CostoBean
{
	private float tarifa;
	private String unidadTarifa;
	private Date vigencia;
	private String condicionPago;
	public float calcularCostoVigente()
	{
		return tarifa;
	
	}
	
	public float calcularCostoFecha(Date fe)
	{
		return tarifa;
	
	}
}
