package bean;
import java.util.List;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : CuentaCorriente.java
//  @ Date : 06/04/2015
//  @ Author : 
//
//




public class CuentaCorrienteBean
{
	private float saldo;
	private int numero;
	private List<MovimientoBean> movimientos;
}
