package bean;
import java.util.List;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Deposito.java
//  @ Date : 06/04/2015
//  @ Author : 
//
//




public class DepositoBean
{
	private List<CargaBean> cargas;
	public void revisarCarga()
	{
	
	}
	
	public void recepcionarCarga(CargaBean c)
	{
	
	}
	
	public void daespacharCarga(CargaBean c)
	{
	
	}
}
