package bean;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Destino.java
//  @ Date : 06/04/2015
//  @ Author : 
//
//




public class DestinoBean
{
	private Object domicilio;
}
