package bean;
import java.util.List;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Empresa.java
//  @ Date : 06/04/2015
//  @ Author : 
//
//




public class EmpresaBean extends ClienteBean
{
	public EmpresaBean(String tipoDocumento, String nroDocumento,
			List<HabilitadoBean> habilitados) {
		super(tipoDocumento, nroDocumento);
		// TODO Auto-generated constructor stub
	}
	private String razonSocial;
	private DireccionBean domicilioComercial;
	private String condiciónIVA;
	public List<DireccionBean> destinosHabilitados;
	public void addDestino(DireccionBean domicilio)
	{
	
	}
}
