package bean;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ItemRemito.java
//  @ Date : 06/04/2015
//  @ Author : 
//
//




public class ItemRemitoBean
{
	private int cantidad;
	private CargaBean carga;
}
