package bean;
import java.util.Date;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Movimiento.java
//  @ Date : 06/04/2015
//  @ Author : 
//
//




public class MovimientoBean
{
	private int valor;
	private String estado;
	private String concepto;
	private Date fecha;
}
