package bean;

import java.util.List;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Ocacional.java
//  @ Date : 06/04/2015
//  @ Author : 
//
//




public class OcacionalBean extends EmpresaBean
{

	public OcacionalBean(String tipoDocumento, String nroDocumento,
			List<HabilitadoBean> habilitados) {
		super(tipoDocumento, nroDocumento, habilitados);
		// TODO Auto-generated constructor stub
	}
}
