package bean;

import java.util.List;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Particular.java
//  @ Date : 06/04/2015
//  @ Author : 
//
//




public class ParticularBean extends ClienteBean
{
	public ParticularBean(String tipoDocumento, String nroDocumento,
			List<HabilitadoBean> habilitados) {
		super(tipoDocumento, nroDocumento);
		// TODO Auto-generated constructor stub
	}
	private String apellido;
	private String nombre;
	private DireccionBean domicilio;
}
