package bean;
import java.util.List;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Proveedor.java
//  @ Date : 06/04/2015
//  @ Author : 
//
//




public class ProveedorBean
{
	private String tipoDocumento;
	private int numeroDocumento;
	private String razonSocial;
	private DireccionBean domicilioComercial;
	private List<ServicioBean> serviciosProvistos;
}
