package bean;
import java.util.Date;
import java.util.List;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Remito.java
//  @ Date : 06/04/2015
//  @ Author : 
//
//




public class RemitoBean
{
	private Object numeroRemito;
	private Date fechaEnvio;
	private ClienteBean remitente;
	private HabilitadoBean destinatario;
	private SucursalBean sucursalOrigen;
	private SucursalBean sucursalDestino;
	private List<ItemRemitoBean> itemsRemito;
	public void confirmarRemito()
	{
	
	}
}
