package bean;
import java.util.Date;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : SolicitudDeCargaConRetiro.java
//  @ Date : 06/04/2015
//  @ Author : 
//
//




public class SolicitudDeCargaConRetiroBean extends SolicitudDeCargaBean
{
	private DireccionBean domicilioCarga;
	private Date fechaRetiro;
	private String rangoHorario;
}
