package bean;
import java.util.List;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Sucursal.java
//  @ Date : 06/04/2015
//  @ Author : 
//
//




public class SucursalBean
{
	private Object nroSucursal;
	private DireccionBean domicilio;
	private EmpleadoBean gerente;
	private EmpleadoBean encargadoDeposito;
	private EmpleadoBean encargadoDespacho;
	private List<EmpleadoBean> empleados;
	private DepositoBean deposito;
	private List<SolicitudDeCargaBean> SolicitudesDeCarga;
	private List<VehiculoBean> vehiculosDisponibles;
	public void nuevaSolicitud()
	{
	
	}
	
	private List<ViajeBean> consultarSolicitudesSinViaje()
	{
		return null;
	
	}
	
	public void designarEncargadoDepósito(EmpleadoBean e)
	{
	
	}
	
	public void designarEncargadoDespacho(EmpleadoBean e)
	{
	
	}
	
	public void designarGerente(EmpleadoBean e)
	{
	
	}
	
	public void generarSolicitudDeCarga()
	{
	
	}
	
	private void recepcionarCarga(CargaBean c)
	{
	
	}
	
	private void despacharCarga(CargaBean c)
	{
	
	}
	
	public List<VehiculoBean> obtenerVehiculosDisponible()
	{
		return vehiculosDisponibles;
	
	}
}
