package bean;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ViajeVehiculoPropio.java
//  @ Date : 06/04/2015
//  @ Author : 
//
//




public class ViajeVehiculoPropioBean extends ViajeBean
{
	private VehiculoBean vehiculo;
	public float calcularPrecio()
	{
		return 0;
	
	}

}
