package bean;
import java.util.Date;
import java.util.List;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Viaje.java
//  @ Date : 06/04/2015
//  @ Author : 
//
//




public abstract class ViajeBean
{
	private SucursalBean sucursalOrigen;
	private SucursalBean sucursalDestino;
	private Date fechaPartida;
	private Date fechaArribo;
	private List<ServicioBean> serviciosAdicionales;
	private List<SolicitudDeCargaBean> solicitudesDeCarga;
	private Date fechaPrioridad;
	protected abstract float calcularPrecio();
	public void addServicios(ServicioBean s)
	{
	
	}
}
