package bean;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ViajeVehiculoContratado.java
//  @ Date : 06/04/2015
//  @ Author : 
//
//




public class ViajeVehiculoContratadoBean extends ViajeBean
{
	private ProveedorBean proveedor;
	private boolean aereo;
	public float calcularPrecio()
	{
		return 0;
	
	}
	
	
}
